<?php
TODA PERSONA TIENE DERECHO: A MANTENER RESERVA SOBRE SUS CONVICCIONES POLÍTICAS, FILOSÓFICAS, RELIGIOSAS O DE CUALQUIER OTRA ÍNDOLE ASÍ COMO A:
REPRESIÓN AL TRÁFICO ILÍCITO DE DROGAS. EL ESTADO COMBATE Y SANCIONA LE TRÁFICO ILÍCITO DE DROGAS. ASIMISMO, REGULA
EDUCACIÓN PARA LA VIDA  Y  EL  TRABAJO.  LOS  MEDIOS  DE  COMUNICACIÓN  SOCIAL.  LA  FORMACIÓN  ÉTICA Y CÍVICA Y LA ENSEÑANZA DE LA CONSTITUCIÓN Y DE LOS DERECHOS HUMANOS SON:
JORNADA ORDINARIA DE TRABAJO. LA JORNADA ORDINARIA DE TRABAJO ES DE 8 HORAS DIARIAS   O   48 HORAS SEMANALES COMO MÁXIMO.  EN  CASO  DE  JORNADAS  ACUMULATIVAS  O  ATÍPICAS,  EL  PROMEDIO DE HORAS TRABAJADAS EN EL PERIODO CORRESPONDIENTE:
EL VOTO ES PERSONAL, IGUAL, LIBRE, SECRETO Y OBLIGATORIO HASTA LOS
SEÑALE LA ALTERNATIVA QUE NO CORRESPONDA: PUEDEN SER SOMETIDOS A REFERÉNDUM:
SUSPENSIÓN DEL EJERCICIO DE LA CIUDADANÍA. EL EJERCICIO DE LA CIUDADANÍA SE SUSPENDE:
LA EXTRADICIÓN SÓLO SE CONCEDE POR EL PODER EJECUTIVO PREVIO INFORME
SE RECONOCEN LOS DERECHOS DE SINDICACIÓN Y HUELGA DE LOS SERVIDORES PÚBLICOS. NO ESTÁN COMPRENDIDOS LOS FUNCIONARIOS DEL ESTADO CON PODER DE  DECISIÓN Y LOS  QUE  DESEMPEÑAN CARGOS DE CONFIANZA O DE DIRECCIÓN, ASÍ COMO
MARQUE LA ALTERNATIVA QUE NO CORRESPONDA. LA REPÚBLICA DEL PERÚ ES:
DEBERES DEL ESTADO. ES DEBER DEL ESTADO ESTABLECER Y EJECUTAR LA POLÍTICA DE FRONTERAS Y PROMOVER LA INTEGRACIÓN, PARTICULARMENTE:
EJERCICIOS DEL PODER DEL ESTADO. NINGUNA  PERSONA,  ORGANIZACIÓN, FUERZA ARMADA, POLICÍA NACIONAL O SECTOR DE LA POBLACIÓN PUEDE ARROGARSE EL EJERCICIO DE ESE  PODER. HACERLO CONSTITUYE
DEFENSA JUDICIAL DEL ESTADO. LA DEFENSA DE LOS INTERESES DEL ESTADO ESTÁ A CARGO DE LOS PROCURADORES PÚBLICOS CONFORME A LEY. EL ESTADO ESTÁ EXONERADO DEL PAGO DE:
ADQUISICIÓN Y RENUNCIA DE LA NACIONALIDAD. LA NACIONALIDAD PERUANA NO SE PIERDE, SALVO POR RENUNCIA EXPRESA ANTE:
RÉGIMEN DE EXCEPCIÓN. ESTADO DE EMERGENCIA, EN CASO DE PERTURBACIÓN DE LA PAZ O DEL ORDEN INTERNO, DE CATÁSTROFE O GRAVES CIRCUNSTANCIAS QUE AFECTAN LA VIDA DE LA NACIÓN. EN ESTA EVENTUALIDAD, PUEDE RESTRINGIRSE O SUSPENDERSE EL EJERCICIO DE LOS DERECHOS CONSTITUCIONALES RELATIVOS:
RÉGIMEN DE EXCEPCIÓN. EL PLAZO DE ESTADO DEL EMERGENCIA NO EXCEDE DE:
RÉGIMEN DE EXCEPCIÓN. EN ESTADO DE EMERGENCIA LAS FUERZAS ARMADAS ASUMEN EL CONTROL DEL ORDEN INTERNO SI ASÍ LO DISPONE:
RÉGIMEN DE EXCEPCIÓN. EL PRESIDENTE DE LA REPÚBLICA, CON ACUERDO DE CONSEJO DE   MINISTROS, PUEDE DECRETAR, POR PLAZO DETERMINADO, EN TODO EL TERRITORIO NACIONAL O EN PARTE DE ÉL, EL ESTADO DE SITIO EN CASO DE:
RÉGIMEN DE EXCEPCIÓN. ESTADO DE SITIO. EL PLAZO CORRESPONDIENTE NO EXCEDE DE:
RÉGIMEN DE EXCEPCIÓN. ESTADO DE SITIO, EN CASO DE INVASIÓN, GUERRA EXTERIOR, GUERRA CIVIL   O PELIGRO INMINENTE DE QUE SE PRODUZCAN , CON MENCIÓN DE LOS DERECHOS FUNDAMENTALES CUYO EJERCICIO:
RÉGIMEN DE EXCEPCIÓN. AL DECRETARSE EL ESTADO DE SITIO, EL CONGRESO SE REÚNE DE PLENO DERECHO. LA PRÓRROGA REQUIERE APROBACIÓN
DETERMINA LOS ALCANCES Y PROCEDIMIENTO DE LA MOVILIZACIÓN PARA EFECTOS DE LA DEFENSA NACIONAL
LAS FUERZAS ARMADAS Y LA POLICÍA NACIONAL NO SON DELIBERANTES. ESTÁN SUBORDINADOS AL:
EL NÚMERO DE EFECTIVOS DE LAS FUERZAS ARMADAS Y DE LA POLICÍA NACIONAL SE FIJA ANUALMENTE POR:
PROCEDE CONTRA  EL HECHO U OMISIÓN, POR PARTE DE CUALQUIER AUTORIDAD, FUNCIONARIO   O PERSONA, QUE VULNERA O AMENAZA LA LIBERTAD INDIVIDUAL O LOS DERECHOS CONSTITUCIONALES CONEXOS
PROCEDE CONTRA EL HECHO U OMISIÓN, POR PARTE DE CUALQUIER AUTORIDAD, FUNCIONARIO O PERSONA, QUE VULNERA O AMENAZA LOS DEMÁS DERECHOS RECONOCIDOS POR LA CONSTITUCIÓN
NO	PROCEDE	CONTRA	NORMAS	LEGALES	NI	CONTRA	RESOLUCIONES   JUDICIALES	EMANADAS	DEL PROCEDIMIENTO REGULAR
PROCEDE POR INFRACCIÓN DE LA CONSTITUCIÓN Y LA LEY, CONTRA LOS REGLAMENTOS, NORMAS ADMINISTRATIVAS Y  RESOLUCIONES Y DECRETOS DE CARÁCTER GENERAL, CUALQUIERA SEA  LA AUTORIDAD DE LA QUE EMANEN
NO LE CORRESPONDE CUESTIONAR LA DECLARACIÓN DEL ESTADO DE EMERGENCIA NI DE SITIO
LOS MIEMBROS DEL TRIBUNAL CONSTITUCIONAL SON ELEGIDOS POR EL CONGRESO DE LA REPÚBLICA CON EL VOTO FAVORABLE
MARQUE LA ALTERNATIVA QUE NO CORRESPONDA. ESTÁN FACULTADOS PARA INTERPONES ACCIÓN DE INCONSTITUCIONALIDAD:
ESTÁ FACULTADO PARA INTERPONER ACCIÓN DE INCONSTITUCIONALIDAD
ESTÁN FACULTADO PARA INTERPONER ACCIÓN DE INCONSTITUCIONALIDAD
CORRESPONDE AL TRIBUNAL CONSTITUCIONAL:
NO PUEDEN SER ELEGIDOS MAGISTRADOS DEL TRIBUNAL CONSTITUCIONAL, LOS JUECES O FISCALES QUE NO HAN DEJADO EL CARGO:
EL EJERCICIO DE LAS ACCIONES DE HÁBEAS CORPUS Y DE AMPARO:
LA POBLACIÓN CIVIL TIENE DERECHO DE INSURGENCIA EN DEFENSA DEL:
LA DEFENSA DE LOS INTERESES DEL ESTADO ESTÁ A CARGO DE:
REGULA EL INGRESO A LA CARRERA ADMINISTRATIVA, Y  LOS  DERECHOS,   DEBERES   Y RESPONSABILIDADES DE LOS SERVIDORES PÚBLICOS:
LOS FUNCIONARIOS Y  SERVIDORES PÚBLICOS QUE SEÑALA LA LEY O QUE ADMINISTRAN O MANEJAN FONDOS DEL ESTADO  O DE  ORGANISMOS  SOSTENIDOS  POR ÉSTE,  DEBEN  HACER  DECLARACIÓN   JURADA DE BIENES Y RENTAS:
PRINCIPIOS INSTITUCIONALES: LA FUNCIÓN POLICIAL SE BRINDA A TRAVÉS DE LA POLICÍA NACIONAL DEL PERÚ, COMO FUERZA PUBLICA UNITARIA YCOHESIONADA
PRINCIPIOS INSTITUCIONALES: LA POLICÍA NACIONAL DEL PERÚ TIENE COMANDOÚNICO
VALORES INSTITUCIONALES: ES EL VALOR QUE ASEGURA SU PRESTIGIO Y REPUTACIÓN; SE CULTIVA MENDIANTE EL CABAL CUMPLIMIENTO DE LA FUNCIÓN POLICIAL
VALORES INSTITUCIONALES: EL SERVICIO POLICIAL DEMANDA LA ACTUACIÓN, ÉTICA PROBA Y CORRECTA
REALIZAR LAS FUNCIONES DE INVESTIGACIÓN POLICIAL POR INICIATIVA PROPIA O BAJO LA  CONDUCCIÓN JURÍDICA DEL  FISCAL, EN CONCORDANCIA CON EL CÓDIGO PROCESAL PENAL Y LAS LEYES DE   LA MATERIA; CONSTITUYE:
INTERVENIR CUANDO EL EJERCICIO DE LA FUNCIÓN POLICIAL ASÍ LO REQUIERA, POR CONSIDERAR QUE SUS EFECTIVOS SE ENCUENTRAN DE SERVICIO EN TODO MOMENTO Y CIRCUNSTANCIA; CONSTITUYE
EJERCER	LA	FUNCIÓN	POLICIAL	EN	TODO	MOMENTO,   LUGAR,	SITUACIÓN   Y	CIRCUNSTANCIA, POR CONSIDERARSE SIEMPRE DE SERVICIO, CONSTITUYE
NO ACATAR DISPOSICIONES QUE CONSTITUYEN UNA MANIFIESTA VIOLACIÓN A LA CONSTITUCIÓN Y A LAS LEYES, CONSTITUYE
MARQUE LA QUE NO CORRESPONDA. SON ÓRGANOS CONSULTIVOS DE LA POLICÍA NACIONAL DE PERÚ
SON AQUELLOS QUE CUMPLEN ACTIVIDADES DE APOYO EN MATERIA DE ASUNTOS INTERNACIONALES, COOPERACIÓN   POLICIAL  INTERNACIONAL,  AVIACIÓN   POLICIAL,   CRIMINALÍSTICA,    INTELIGENCIA, FORMACIÓN POLICIAL, DOCTRINA Y SANIDAD, PARA EL EJERCICIO EFICIENTE Y OPORTUNO DE LA FUNCIÓN POLICIAL
REALIZAN FUNCIONES TÉCNICAS, NORMATIVAS Y OPERATIVAS NECESARIAS PARA EL CUMPLIMIENTO DE LOS OBJETIVOS ENCOMENDADOS A LA POLICÍA NACIONAL  DEL PERÚ EN APLICACIÓN DE LAS NORMAS SUSTANTIVAS QUE ASÍ LO ESTABLECEN
ES UNA DE LAS ESPECIALIDADES FUNCIONALES DEL PERSONAL DE ARMAS DE LA POLICÍA NACIONAL DEL PERÚ
ESTABLECE LAS NORMAS Y PROCEDIMIENTOS  DISCIPLINARIOS DESTINADOS A REGULAR, PREVENIR, INVESTIGAR Y  SANCIONAR LAS INFRACCIONES EN LA QUE INCURRE EL PERSONAL DE   LA   POLICÍA NACIONAL DEL PERÚ
PRACTICAR Y EMITIR  PERITAJES  OFICIALES  DE  CRIMINALÍSTICA  PARA  EFECTO  DE  PROCESOS  JUDICIALES Y OTROS DERIVADOS DE LA FUNCIÓN POLICIAL; CONSTITUYE
ES EL ÓRGANO ENCARGADO DE LA GESTIÓN ADMINISTRATIVA Y DOCUMENTARIA DE LA POLICÍA NACIONAL DEL PERÚ 
LA  POLICÍA  NACIONAL  DEL  PERÚ  PLANIFICA  Y  EJECUTA  SUS  ACCIONES   OPERATIVAS   Y  ADMINISTRATIVAS DE  MANERA COORDINADA Y ALINEADAS CON LAS POLÍTICAS   NACIONALES,   SECTORIALES   Y   LOS INTERESES  DEL   ESTADO,   GOBIERNOS  REGIONALES  Y  LOCALES;  CONSTITUYE  EL  PRINCIPIO INSTITUCIONAL DE:
TENER PASE LIBRE EN VEHÍCULOS DE TRANSPORTE DE SERVICIO PÚBLICO, CORRESPONDE A:
INTERVENIR  EN ASUNTOS DONDE SUS INTERESES   PERSONALES,  LABORALES,  ECONÓMICOS  O FINANCIEROS PUDIERAN ESTAR EN CONFLICTO CON EL CUMPLIMIENTO DE LOS DEBERES Y FUNCIONES A SU CARGO; CORRESPONDE A:
USAR  EL  UNIFORME  REGLAMENTARIO,  LOS  DISTINTIVOS  Y  LAS  DIVISAS  DE  LA  POLICÍA   NACIONAL    DEL PERÚ ASÍ COMO EL ARMAMENTO PROVISTO POR EL ESTADO, PARA LA REALIZACIÓN DE LAS ACTIVIDADES DISTINTAS A LA FUNCIÓN POLICIAL; CONSTITUYE:
CUMPLEN  FUNCIONES  ESPECÍFICAS ASIGNADAS DENTRO DE UN ÁMBITO TERRITORIAL DETERMINADO. ACTÚAN EN REPRESENTACIÓN Y POR DELEGACIÓN DENTRO  DEL  TERRITORIO  DE  SU  JURISDICCIÓN,  SOBRE EL CUAL EJERCEN MANDO Y COMANDO
ES LA ATRIBUCIÓN DEL ESTADO EJERCIDA  POR  LA  POLICÍA  NACIONAL  DEL  PERÚ  QUE  FACULTA  EL  USO  DE LA FUERZA DE MANERA LEGÍTIMA EN EL CUMPLIMIENTO DE SU FINALIDAD PARA LA CONSERVACIÓN DEL ORDEN INTERNO Y GARANTIZAR EL FUNCIONAMIENTO DE LOS PODERES DEL ESTADO
EL PRESENTE DECRETO LEGISLATIVO ESTABLECE Y NORMA LA ESTRUCTURA, ORGANIZACIÓN, COMPETENCIAS, FUNCIONES Y ATRIBUCIONES DE LA POLICÍA NACIONAL DEL PERÚ; NOS REFERIMOS A:
LA FUNCIÓN POLICIAL SE DESARROLLA EN EL MARCO DE SU FINALIDAD FUNDAMENTAL DESCRITA Y DEFINIDA EN EL:
LA POLICÍA NACIONAL DEL PERÚ EJERCE COMPETENCIA FUNCIONAL Y EXCLUSIVA A NIVEL NACIONAL EN MATERIA DE:
LA POLICÍA NACIONAL DEL PERÚ EJERCE COMPETENCIA FUNCIONAL Y EXCLUSIVA A NIVEL NACIONAL EN MATERIA DE:
LA POLICÍA NACIONAL DEL PERÚ EJERCE COMPETENCIA COMPARTIDA EN MATERIA DE:
FISCALIZAR EL CUMPLIMENTO DE LAS NORMAS DE TRÁNSITO POR PARTE DE LOS USUARIOS DE LA INFRAESTRUCTURA VIAL, CORRESPONDE:
ES EL ÓRGANO ENCARGADO DE EFECTUAR EL CONTROL GUBERNAMENTAL EN LA POLICÍA   NACIONAL   DEL PERÚ,  PROMOVIENDO LA CORRECTA Y TRANSPARENTE GESTIÓN DE LOS RECURSOS   Y   BIENES   DEL ESTADO
REALIZAR  INSPECCIONES  DE CONTROL INTERNO A LOS ÓRGANOS Y UNIDADES ORGÁNICAS QUE CONFORMAN LA POLICÍA NACIONAL DEL PERÚ PARA VERIFICAR LA CALIDAD, EFICIENCIA Y EFICACIA EN EL EJERCICIO DE LA FUNCIÓN POLICIAL; CORRESPONDE A:
LOS ÓRGANOS DESCONCENTRADOS DE LA POLICÍA NACIONAL SE ORGANIZAN EN:
SON	UNIDADES	ORGÁNICAS	CUYA	JURISDICCIÓN	SE	ENCUENTRAN	CONSTITUIDA	POR	EL	ÁMBITO GEOGRÁFICO DE UN DEPARTAMENTO, CON EXCEPCIÓN DE LAS REGIONES POLICIALES DE LIMA Y CALLAO
SE CREAN DE MANERA EXCEPCIONAL Y TEMPORAL, EN EL MISMO NIVEL Y ORGANIZACIÓN FUNCIONAL DE UNA REGIÓN POLICIAL
ES  EL  ÓRGANO DE CARÁCTER TÉCNICO, NORMATIVO Y OPERATIVO, ENCARGADO DE   PLANIFICAR, COMANDAR Y SUPERVISAR LAS OPERACIONES POLICIALES EN MATERIA  DE  SEGURIDAD DEL ESTADO; SEGURIDAD INTEGRAL; SEGURIDAD CIUDADANA; OPERACIONES POLICIALES, ENTRE OTROS
SE BASA  UN  CONJUNTO  DE  PRINCIPIOS, NORMAS, PROCESOS  Y  CONDICIONES  QUE  PERMITEN AL PERSONAL DE LA POLICÍA NACIONAL DEL PERÚ, ACCEDER DE MANERA SUCESIVA A CADA GRADO. ESTA DEFINICIÓN CORRESPONDE A:
LA POLICÍA NACIONAL DEL PERÚ BRINDA EL SERVICIO DE  ASESORÍA  Y DEFENSA LEGAL GRATUITA AL PERSONAL DE LA POLICÍA NACIONAL QUE  AFRONTA  UN PROCESO PENAL O CIVIL DERIVADO DEL CUMPLIMIENTO DE LA FUNCIÓN POLICIAL, ESTA DEFINICIÓN CORRESPONDE A:
LOS PROCEDIMIENTOS ADMINISTRATIVOS Y SERVICIOS PRESTADOS EN EXCLUSIVIDAD QUE SE BRINDEN A TRAVÉS DE LA POLICÍA NACIONAL DEL PERÚ SON APROBADOS POR:
LOS GRADOS, HONORES, TRATAMIENTO, PREEMINENCIAS, PRERROGATIVAS, REMUNERACIONES Y LAS PENSIONES INHERENTES A LOS OFICIALES Y SUBOFICIALES DE LAS FUERZAS ARMADAS Y DE LA POLICÍA NACIONAL SON:
EL PERSONAL CIVIL QUE REALIZA LABORES  ESPECÍFICAS DE APOYO A LA FUNCIÓN POLICIAL SE DENOMINARÁ:
A QUÉ VALOR INSTITUCIONAL CORRESPONDE  LA  SIGUIENTE  DEFINICIÓN:  EL  SERVICIO POLICIAL  DEMANDA LA ACTUACIÓN ÉTICA, PROBA Y CORRECTA
POSEER, PORTAR Y USAR ARMAS DE FUEGO, DE CONFORMIDAD CON LA CONSTITUCIÓN Y LA LEY; CONSTITUYE:
PRELACIÓN EXISTENTE ENTRE EL PERSONAL, EN ATENCION A SU CATEGORIA, JERARQUIA, GRADO Y TIEMPO DE SERVICIO, SE REFIERE A:
UBICACIÓN DEL PERSONAL EN SITUACIÓN DE ACTIVIDAD EN UN CARGO ESPECIFICO, ACORDE A LAS ESPECIALIDADES FUNCIONALES, AL CUADRO DE ORGANIZACIÓN Y AL CUADRO DE PERSONAL Y QUE SE EJECUTA ANUALMENTE CONFORME A LOS CAMBIO GENERALES DE COLOCACIÓN, SE REFIERE A:
FALTA DE CAPACIDAD PROFESIONAL O TÉCNICA DEL PERSONAL PARA EJERCER LA FUNCIÓN POLICIAL
CONJUNTO DE ACTIVIDADES QUE EJECUTA EL PERSÓNAL EN SITUACIÓN DE ACTIVIDAD, PARA EL CUMPLIMIENTO DE SU FINALIDAD Y MISIÓN INSTITUCIONAL, SE REFIEREA:
PERSONAL EGRESADO DE LAS ESCUELAS TÉCNICO SUPERIOR   DE   SUBOFICIALES   DE   LA   POLICIA NACIONAL DEL PERU, SE REFIERE A:
NINGUNA  DISPOSICIÓN DEL   PRESENTE   DECRETO   LEGISLATIVO   PUEDE,   EN SU   APLICACIÓN,   GENERAR ACTO DE DISCRIMINACIÓN, SE REFIERE AL PRINCIPIO DE:
EL INGRESO, LA PERMANENCIA, Y LOS ASCENSOS  EN LA CARRERA, SE FUNDAMENTAN EN LOS  MERITOS Y EN LAS CAPACIDADES PERSONALES, PROFESIONALES Y TECNICAS, SE REFIERE AL PRINCIPIO DE:
ASIGNACION A UN CARGO CON CARÁCTER TEMPORAL POR NECESIDAD DEL SERVICIO O A SOLICITUD DEL INTERESADO POR UN PERIODO NO MAYOR A NOVENTA (90) DIAS CALENDARIO. SE REFIERE A:
TIENE POR FINALIDAD DISEÑAR LA ESTRUCTURA Y ORGANIZACIÓN DE LA CARRERA, CON EL FIN DE ESTABLECER  LAS OPORTUNIDADES DEL   DESARROLLO   PERSONAL,   PROFESIONAL   Y   TECNICO,   CON ENFASIS EN LA DISCIPLINA Y LOS MÉRITOS, SE REFIERE A:
PERTENECE A LA JERARQUIA DE OFICIALES SUPERIORES:
PERTENECE A LA JERARQUIA DE SUBOFICIALES SUPERIORES:
SE INICIA CON  EL  ALTA  COMO  ALFEREZ  O  SUBOFICIAL  DE  TERCERA  DE  ARMAS;  O  POR  HABER   OBTENIDO LA EFECTIVIDAD EN LOS GRADOS DE MAYOR, CAPITAN O SUBOFICIAL DE TERCERA DE SERVICIOS, SEGÚN CORRESPONDA; EN AMBOS CASOS MEDIANTE LA EXPEDICIÓN DE LA RESOLUCION ADMINISTRATIVA CORRESPONDIENTE; SE REFIERE A:
ES EL PERIODO EN EL QUE PERMANECE EL PERSONAL PROFESIONAL Y TECNICO QUE SE INCORPORA A LA POLICIA NACIONAL DEL PERU, HASTA LA OBTENCIÓN DE LA EFECTIVIDAD EN EL GRADO, SE REFIERE A:
CUAL ES EL PERIODO EN CONDICIÓN DE ASIMILADO PARA LOS SUBOFICIALES DE SERVICIO:
ES LA CONDICION LABORAL DEL PERSONAL DE LA POLICÍA NACIONAL DEL PERÚ, EN SITUACIÓN DE ACTIVIDAD, EN FUNCION A SU CATEGORIA Y GRADO, SE REFIERE A:
LA ASIGNACIÓN Y REASIGNACIÓN DE LOS OFICIALES GENERALES SE APRUEBA POR:
ES UNA CAUSAL DE ASIGNACION Y REASIGNACION:
ES UNA CAUSAL DE ASIGNACION Y REASIGNACION:
EN LOS LUGARES DONDE NO SE LOGREN CUBRIR COMISARIAS CON OFICIALES DE ARMAS, SE ASIGNARAN SUBOFICIALES DE ARMAS EN LA JERARQUÍA DE:
EL PERSONAL  AL  RETORNAR  DE  LA  MISION  DE  ESTUDIOS  DEBE  SER  ASIGNADO  A  UNA  UNIDAD  ACORDE CON LA CAPACITACION  RECIBIDA; ASI MISMO, REPLICAR SUS CONOCIMIENTOS EN LOS ORGANOS   DE GESTION ACADEMICA DEL:
EL PERSONAL AUXILIAR DESIGNADO  PARA EN LAS  AGREGADURÍAS  POLICIALES  DEBEN  TENER EL GRADO DE:
 SON  RECONOCIMIENTOS QUE OTORGAN LOS DIVERSOS NIVELES DEL COMANDO   INSTITUCIONAL, ORIENTADOS A DISTINGUIR LOS ACTOS MERITORIOS DEL PERSONAL.  TIENEN  CARÁCTER MOTIVADOR, SE REFIERE A:
LA CONDECORACION DE LA "ORDEN AL MERITO DE LA POLICÍA NACIONAL DEL PERU" SE OTORGA EN LA CATEGORIA SIGUIENTE:
LA CONDECORACION DE LA "ORDEN AL MERITO DE LA POLICÍA NACIONAL DEL PERU" SE OTORGA EN LA CATEGORIA SIGUIENTE:
ES EL ASCENSO TIENE PORFINALIDAD:
LOS ASCENSO SE CLASIFICAN DE LA SIGUIENTE MANERA:
QUÉ TIEMPO MINIMO DE AÑOS DE  SERVICIOS  EFECTIVOS  Y  REALES  EN  EL  GRADO,  CONSIDERADOS  AL  31 DE DICIEMBRE DEL AÑO DEL PROCESO, DEBE TENER UN ALFÉREZ DE ARMAS, PARA ASCENDER AL GRADO INMEDIATO SUPERIOR:
EL PERSONAL FEMENINO DE LA POLICÍA NACIONAL DEL PERU QUE PARTICIPA EN EL PROCESO DE ASCENSOS ENCONTRÁNDOSE EN ESTADO DE GESTACIÓN, ES EXONERADA DE:
LA CARRERA DEL PERSONAL DE LA POLICIA NACIONAL DEL PERU TERMINA POR:
ES LA CONDICION EN QUE SE ENCUENTRA EL PERSONAL DE LA POLICIA NACIONAL DEL PERU:
EN ATENCION A LA NATURALEZA DE SUS FUNCIONES, EL PERSONAL DE ARMAS SE CLASIFICA EN:
ES LA CONDICIÓN DEL PERSONAL DE LA POLICIA NACIONAL DEL PERU EN CUADROS Y FUERA DE CUADROS:
EL PERSONAL DE LA POLICIA NACIONAL DEL PERU PASA A LA SITUACION DE DISPONIBILIDAD POR LAS CAUSALES DE:
PUEDE  DENEGARSE EL PASE A LA SITUACIÓN DE DISPONIBILIDAD POR LA CAUSAL A SU SOLICITUD CUANDO  LAS CIRCUNSTANCIAS ASI LO EXIJAN, EN ATENCION A LOS   REGÍMENES   DE   EXCEPCIÓN PREVISTOS EN LA CONSTITUCIÓN POLÍTICA DEL PERU Y EN LOS CASOS EN QUE SE VEA COMPROMETIDO EL:
ES LA CONDICION DEL PERSONAL DE LA POLICIA NACIONAL DEL PERU QUE SE ENCUENTRA APARTADO DEFINITIVAMENTE DEL SERVICIO POLICIAL. ES DE CARÁCTER IRREVERSIBLE:
LOS SUBOFICIALES SUPERIORES DE LA POLICIA NACIONAL DEL PERU, PASARAN A LA SITUACION DE RETIRO POR LIMITE DE EDAD EN EL GRADO , EN ATENCION A LA EDAD MAXIMA DE:
EL PERSONAL QUE CUMPLE CUARENTA (40) AÑOS DE SERVICIO REALES Y EFECTIVOS EN LA POLICIA NACIONAL DEL PERU PASA:
ES LA ACCIÓN ADMINISTRATIVA QUE SE APLICA AL PERSONAL DE LA POLICÍA NACIONAL DEL PERU, POR SANCIÓN DISCIPLINARIA O POR INSUFICIENCIA DISCIPLINARIA:
EL MINISTRO DEL INTERIOR CREA LA COMISIÓN SECTORIAL, ESTABLECIENDO SU CONFORMACIÓN Y SUS ATRIBUCIONES DE CONFORMIDAD A LO ESTABLECIDO EN LA PRESENTE NORMA. ESTÁ CONFORMADA POR PERSONAL POLICIAL DE ARMAS Y DE SERVICIOS EN EL GRADO DE TENIENTE GENERAL, GENERAL Y CORONEL, SEGÚN CORRESPONDA:
LA COMISIÓN SECTORIAL PROPONE SIN PERJUICIO DE LAS CAUSALES ESTABLECIDAS EN EL DECRETO LEGISLATIVO N° 1149 –LEY DE LA CARRERA Y SITUACIÓN DE PERSONAL DE LA POLICÍA NACIONAL DEL PERÚ Y SU REGLAMENTO EL PASE A LA SITUACIÓN DE RETIRO POR FALTA DE IDONEIDAD EN BASE AL SIGUIENTE CRITERIO:
CAUSAR UN DAÑO POR EVITAR OTRO MAYOR, SIEMPRE QUE ESTE ÚLTIMO SEA EFECTIVO Y NO SE PUEDA RAZONABLEMENTE EXIGIR AL AUTOR EL SACRIFICIO DEL BIEN AMENAZADO Y QUE, DADAS LAS CIRCUNSTANCIA, NO HAYA PODIDO EMPLEAR OTRO MEDIO MENOS PERJUDICIAL ES UNA:
LAS RESOLUCIONES DEL INICIO DEL PROCEDIMIENTO, LA QUE PONE FIN AL MISMO O AQUELLAS QUE SE CONSIDERAN NECESARIAS DE  COMUNICAR A  LOS  INTERESADOS  , SE TIENEN POR   BIEN  NOTIFICADAS   EN LAS SIGUIENTES CIRCUNSTANCIAS:
PARA EL PROCEDIMIENTO ADMINISTRATIVO  DISCIPLINARIO  SUMARIO,  LA  ETAPA  DE INVESTIGACIÓN TIENE UN PLAZO MÁXIMO DE:
LAS  MEDIDAS  PREVENTIVAS  SON DISPOSICIONES  ADMINISTRATIVAS	DE CARÁCTER PROVISIONAL QUE SE IMPONEN POR LA PRESUNTA COMISIÓN DE INFRACCIONES MUY GRAVES PUEDEN SER:
PARA IMPONER LA MEDIDA PREVENTIVA DE SUSPENSIÓN TEMPORAL DEL SERVICIO DEBERÁ TENERSE EN CUENTA LA PRESENCIA DE ALGUNOS DE LOS ELEMENTOS SIGUIENTES:
PUEDE SER OBVIADO, CUANDO LAS SOLICITUDES SEAN NEGADAS O DEMORADAS INJUSTIFICADAMENTE POR EL SUPERIOR JERÁRQUICO A QUIEN SE RECURRIÓ
IMPLICA LA DISMINUCIÓN DE UN PUNTO Y TRES DÉCIMAS (1.3) DE LA NOTA ANUAL DE DISCIPLINA
SON ACCIONES U  OMISIONES   QUE   ATENTAN  CONTRA  LAS  OBLIGACIONES  Y  DEBERES,  ESTABLECIDOS  EN EL ORDENAMIENTO LEGAL  DE LA POLICÍA NACIONAL DEL PERÚ, Y ESPECIALMENTE AQUELLAS RELACIONADAS CON LOS BIENES JURÍDICOS PROTEGIDOS POR LA PRESENTE NORMA:
TENDRÁ COMO FUNCIÓN SERVIR DE ENLACE ENTRE LOS ÓRGANOS DE INVESTIGACIÓN Y   EL   TRIBUNAL, BRINDAR SOPORTE TÉCNICO ADMINISTRATIVO PARA LA PROYECCIÓN DE LAS RESOLUCIONES QUE DEBAN EMITIRSE , CITAR A SESIÓN, DISPONER LA REALIZACIÓN DE LAS NOTIFICACIONES CORRESPONDIENTES :
LAS  ACCIONES PREVIAS SON   DILIGENCIAS   QUE   REALIZAN   LOS   ÓRGANOS   DE   INVESTIGACIÓN COMPETENTE CON LA FINALIDAD  DE IDENTIFICAR, UBICAR Y ACOPIAR INDICIOS, EVIDENCIAS, PRUEBAS   Y OTROS QUE SE PUEDAN UTILIZAR PARA EL INICIO DEL PROCEDIMIENTO ADMINISTRATIVO DISCIPLINARIO, ESTAS PUEDEN SER:
LAS	CIRCUNSTANCIAS	EXIMENTES	DE	RESPONSABILIDAD ADMINISTRATIVO	DISCIPLINARIA	SON	LAS SIGUIENTES:
SE CONSIDERAN CIRCUNSTANCIAS AGRAVANTES LAS SIGUIENTES:
SI DENTRO DE UNA INVESTIGACIÓN SE IDENTIFICAN NUEVOS HECHOS QUE PUEDAN SE CONSIDERADOS COMO UNA INFRACCIÓN MAS GRAVE DE LA QUE SE INVESTIGA, SE REMITIRÁN LOS ACTUADOS AL:
EN   SEGUNDA   INSTANCIA   LA  INSPECTORÍA   MACRO	REGIONAL   COMPETENTE	EMITIRÁ LA RESOLUCIÓN CORRESPONDIENTE EN UN PLAZO DE:
LAS INFRACCIONES SON SANCIONADAS CON SUJECIÓN A LOS PROCEDIMIENTOS ESTABLECIDOS EN LA PRESENTE NORMA, RESPETÁNDOSE LAS GARANTÍAS Y DERECHOS DEL DEBIDO PROCEDIMIENTO :
LAS INFRACCIONES DISCIPLINARIAS SEGÚN SU GRAVEDAD SE CLASIFICAN EN:
EL CONOCIMIENTO DE LA COMISIÓN DE  LA  UNA INFRACCIÓN OBLIGA EL INICIO INMEDIATO DEL PROCEDIMIENTO       ADMINISTRATIVO      DISCIPLINARIO      CORRESPONDIENTE      Y	COMPROMETE	LA RESPONSABILIDAD DEL SUPERIOR :
OBEDECERÁ LAS ORDENES RECIBIDAS SIEMPRE QUE NO SEAN CONTRARIAS A LO SEÑALADO EN LA CONSTITUCIÓN POLÍTICA DEL PERÚ Y LA NORMATIVA VIGENTE Y DARÁ CUENTA DE SU CUMPLIMIENTO  AL SUPERIOR QUE LA IMPARTIÓ
MEDIANTE EL CUAL NADIE DEBE SE DISCRIMINADO POR MOTIVO DE ORIGEN, RAZA, SEXO, IDIOMA, RELIGIÓN, OPINIÓN, CONDICIÓN ECONÓMICA O DE CUALQUIER OTRAÍNDOLE
SON LOS MANDATOS O REGLAS DE CUMPLIMIENTO OBLIGATORIO DEL PERSONAL POLICIAL DENTRO Y FUERA DEL SERVICIO, GARANTIZA EL RESPETO DE LOS BIENES JURÍDICOS PROTEGIDOS:
LA PRESENTE LEY SE FUNDAMENTA EN LA NECESIDAD DE PRIVILEGIAR Y  SALVAGUARDAR LOS BIENES JURÍDICOS PROTEGIDOS, CONSTITUIDOS POR LA ÉTICA POLICIAL, LA  DISCIPLINA  POLICIAL, EL SERVICIO POLICIAL Y LA IMAGEN INSTITUCIONAL, COMO BIENES JURÍDICOS
ESTABLECER  LAS NORMAS Y PROCEDIMIENTOS ADMINISTRATIVOS   DISCIPLINARIOS   DESTINADOS   A PREVENIR, REGULAR Y SANCIONAR LAS INFRACCIONES COMETIDAS POR  EL  PERSONAL DE  LA POLICIA NACIONAL DEL PERÚ
EL PERSONAL DE LA POLICÍA NACIONAL DEL PERÚ, ESTÁ PROHIBIDO DE PERTENECER A PARTIDOS, AGRUPACIONES U OTRAS ORGANIZACIONES DE CARÁCTER POLÍTICO, ASÍ COMO PARTICIPAR EN ACTIVIDADES POLÍTICAS  PARTIDARIAS,  SINDICALES,  MANIFESTACIONES  PÚBLICAS, HUELGAS O   PETICIÓN  EN CONJUNTO, ASÍ COMO USAR SU PROFESIÓN O CONOCIMIENTOS CONTRA LOS INTERESES DE LA INSTITUCIÓN POLICIAL
LA  FACULTAD  DISCIPLINARIA  SANCIONADORA  PARA  INFRACCIONES   LEVES   ES   INHERENTE   AL   PERSONAL DE LA POLICÍA NACIONAL DEL PERÚ, EN SITUACIÓN DE ACTIVIDAD,  EN SU CONDICIÓN DE SUPERIOR JERÁRQUICO, ES EJERCIDA:
SON AQUELLOS QUE NORMAN LAS RELACIONES INTERNAS Y EXTERNAS ENTRE LOS MIEMBROS DE LA
LOS JEFES DE LAS UNIDADES POLICIALES AL ASUMIR EL CARGO, PRESENTAN SU SALUDO EN FORMA PERSONAL O POR ESCRITO A LAS:
LA ANTIGÜEDAD EN EL GRADO. - DE PERSISTIR LA IGUALDAD , LA ANTIGÜEDAD SE ESTABLECE POR EL:
DEBEN CUMPLIRSE EN EL TIEMPO, LUGAR Y MODO INDICADO POR EL SUPERIOR
LA RESOLUCIÓN DE SANCIÓN POR INFRACCIÓN GRAVE Y MUY GRAVE FIRME DEBIDAMENTE NOTIFICADA SURTE EFECTO
EN LA SANCIÓN ESCRITA QUE IMPONE EL SUPERIOR JERÁRQUICO U ÓRGANO DISCIPLINARIO COMPETENTE AL INFRACTOR POR LA COMISIÓN DE INFRACCIONES LEVES
SE IMPONE CUANDO EL INVESTIGADO SE ENCUENTRA PRIVADO DE SU LIBERTAD POR MANDATO DEL ÓRGANO JURISDICCIONAL, SIN SENTENCIA CONDENATORIA FIRME
SE DISPONEN DESPUÉS DE NOTIFICADA LA RESOLUCIÓN DE INICIO DEL PROCEDIMIENTO ADMINISTRATIVO DISCIPLINARIO, NO CONSTITUYEN DEMÉRITO NI SANCIÓN ADMINISTRATIVA
REQUISITOS PARA SER MIEMBRO DEL TRIBUNAL DE DISCIPLINA POLICIAL
EL PERSONAL DE LA POLICIA NACIONAL DEL PERÚ, PODRÁ INFORMAR O DAR  ENTREVISTAS  A  TRAVÉS DE LOS MEDIOS DE COMUNICACIÓN SOCIAL CUANDO TENGAN:
ES LA  REPRESENTACIÓN ANTE LA  OPINIÓN PÚBLICA DEL ACCIONAR DEL PERSONAL DE LA   POLICIA NACIONAL  DEL  PERÚ.  CONSTITUYE  LA  BASE  PRINCIPAL  DE  LA  RELACIÓN  DE  CONFIANZA   Y  LEGITIMIDAD QUE DEBE IMPERAR ENTRE LA INSTITUCIÓN, SU PERSONAL Y LA SOCIEDAD EN GENERAL,   CONSTITUIDA SOBRE UNA SÓLIDA DISCIPLINA Y UN SERVICIO EFICIENTE Y OPORTUNO
SON LOS PRINCIPIOS RECTORES DE LA LEY DE RÉGIMEN DISCIPLINARIO DE LA PNP: EL SUPERIOR Y LOS ORGANOS DISCIPLINARIOS DEBEN ACTUAR CON RESPETO A LA CONSTITUCIÓN POLÍTICA DEL PERÚ, LA LEY Y AL DERECHO, DENTRO DE LAS FACULTADES QUE LE ESTÉN ATRIBUIDAS Y DE ACUERDO CON LOS FINES PARA LOS QUE LES FUERON CONFERIDAS:
BIENES JURÍDICOS PROTEGIDOS: EL SERVICIO POLICIAL ES EL CONJUNTO DE ACTIVIDADES QUE EJECUTA EL PERSONAL DE LA POLICÍA NACIONAL DEL PERÚ EN SITUACIÓN DE ACTIVIDAD PARA EL CUMPLIMIENTO DE LA MISIÓN Y FUNCIONES INSTITUCIONALES, DE ACUERDO A LO ESTIPULADO EN LA CONSTITUCIÓN POLÍTICA DEL PERÚ, LAS LEYES Y REGLAMENTOS, NOS REFERIMOS A:
SON LOS MANDATOS O REGLAS DE CUMPLIMIENTO OBLIGATORIO DEL PERSONAL POLICIAL DENTRO Y FUERA DEL SERVICIO, GARANTIZA EL RESPETO DE LOS BIENES JURÍDICOS PROTEGIDOS:
TIENE SU SEDE PRINCIPAL EN LA CAPITAL DE LA REPÚBLICA, PUDIENDO CONTAR CON SALAS DESCENTRALIZADAS A NIVEL NACIONAL. EL REGLAMENTO DISPONDRÁ LAS CONDICIONES PARA CREACIÓN DE SALAS, EN FUNCIÓN A LA CARGA PROCESAL:
SON DILIGENCIAS QUE REALIZAN LOS ÓRGANOS DE INVESTIGACIÓN COMPETENTES CON LA FINALIDAD DE IDENTIFICAR, UBICAR Y ACOPIAR INDICIOS, EVIDENCIAS, PRUEBAS Y OTROS QUE PUEDAN SER UTILIZADOS PARA EL INICIO DEL PROCEDIMIENTO ADMINISTRATIVO DISCIPLINARIO:
DECRETO LEGISLATIVO QUE TIENE POR OBJETO NORMAR LA FORMACIÓN PROFESIONAL DE LA POLICIA NACIONAL DEL PERU, ESTABLECIENDO SU FINALIDAD Y OBJETIVOS:
ES EL DECRETO LEGISLATIVO QUE SE APLICA A LOS ESTUDIANTES, DOCENTES Y PERSONAL DE LA POLICIA NACIONAL DEL PERU
ES EL  PROCESO  EDUCATIVO  CON  AUTONOMÍA  ACADÉMICA,  NORMATIVA  Y   ADMINISTRATIVA   QUE   TIENE COMO FINALIDAD LA PREPARACION , INTEGRACIÓN, ACTUALIZACIÓN, ESPECIALIZACION Y PERFECCIONAMIENTO  DE LA POLICIA NACIONAL DEL PERU EN EL NIVEL SUPERIOR DEL   SISTEMA EDUCATIVO, SE REFIERE A:
LA FORMACION PROFESIONAL POLICIAL TIENE COMO PRINCIPIOS:
ES  EL  ORGANO  DE  GESTION   EDUCATIVA  ENCARGADO  DE  ORGANIZAR,  IMPARTIR,   EVALUAR  Y  CERTIFICAR LA FORMACION PROFESIONAL DE  LOS  ESTUDIANTES  Y  PERSONAL  DE  LA  POLICIA  NACIONAL  DEL  PERU, SE REFIERE A:
ESTA FACULTADA A OTORGAR A NOMBRE DE LA NACION LOS GRADOS ACADEMICOS Y LOS TITULOS PROFESIONALES EQUIVALENTES A  LOS  OTORGADOS POR LAS UNIVERSIDADES Y LAS ESCUELAS E INSTITUTOS  DE NIVEL SUPERIOR DEL SISTEMA EDUCATIVO, PARA OFICIALES Y SUBOFICIALES DE   LA POLICIA NACIONAL DEL PERU, ES LA:
LA ESCUELA NACIONAL DE FORMACION PROFESIONAL POLICIAL, DEPENDE DE:
TIENE UN CONSEJO SUPERIOR DE FORMACIÓN PROFESIONAL COMO ÓRGANO MAXIMO DE COORDINACIÓN, GESTIÓN, SUPERVISIÓN Y EJECUCIÓN ACADEMICA Y ADMINISTRATIVA DE LAS DEMÁS, ES LA:
EL INGRESO A LA ESCUELA NACIONAL DE FORMACIÓN PROFESIONAL POLICIAL SE REALIZA MEDIANTE:
SON LOS PROFESIONALES QUE EJERCEN LAS FUNCIONES DE ENSEÑANZA, ASESORIA, INVESTIGACIÓN, MEJORAMIENTO  CONTINUO DEL PROCESO FORMATIVO Y PROYECCIÓN SOCIAL   EN   LA   ESCUELA,   SE REFIERE A:
QUIENES HAYAN CUMPLIDO TODOS LOS REQUISITOS SEÑALADOS EN LAS NORMAS QUE REGULAN LOS PROCESOS DE ADMISIÓN, SUPERAN SATISFACTORIAMENTE SUS ETAPAS DE SELECCIÓN Y SE ENCUENTRAN MATRICULADOS EN ALGUNA DE ELLAS, SE LLAMAN:
LAS INFRACCIONES PARA LOS ESTUDIANTES DE LA ESCUELA SE CLASIFICAN EN :
NO PUEDE RESTRINGIRSE O RETIRARSE LA CONDICIÓN DE ESTUDIANTES POR HECHOS VINCULADOS A:
LOS GRADOS Y TITULOS PROFESIONALES OBTENIDOS POR LOS EGRESADOS DE LA ESCUELA NACIONAL DE FORMACIÓN PROFESIONAL POLICIAL SE INSCRIBEN EN LOS:
SE OTORGA EN ATENCION AL CUADRO DE MERITOS DE INGRESO O ACADÉMICO:
LA ESCUELA NACIONAL DE FORMACION PROFESIONAL POLICIAL, A TRAVÉS DE SUS ESCUELAS PUEDE SUSCRIBIR:
SON APROBADOS  POR LA ESCUELA NACIONAL DE FORMACION PROFESIONAL   POLICIAL  Y   FORMULADOS POR  LAS  ESCUELAS,  TENIENDO  EN  CONSIDERACIÓN  LAS    COMPETENCIAS,    CONOCIMIENTOS,    HABILIDADES Y DESTREZAS REQUERIDOS PARA EL ADECUADO DESEMPEÑO DE LA FUNCIÓN POLICIAL Y LAS ESPECIALIDADES QUE SE DEFINAN PARA EL EJERCICIO EN LA CARRERA, SE REFIERE A:
PROMUEVE LA INVESTIGACIÓN E INNOVACIÓN EN LAS AREAS DEL CONOCIMIENTO QUE FORMAN  PARTE DE SUS PROGRAMAS ACADÉMICOS:
ES INTEGRAL Y CONTINUA, DESTINADA A ESTIMULAR Y DESARROLLAR LAS CAPACIDADES, APTITUDES Y ACTITUDES CRITICAS Y CREATIVAS EN LOS ESTUDIANTES DE LA ESCUELA NACIONAL DE FORMACIÓN PROFESIONAL POLICIAL, SE REFIERE A:
LOS ESTUDIANTES  QUE  HAYAN  CONCLUIDO  SATISFACTORIAMENTE  SU  PLAN  CURRICULAR  Y  COMPLETADO LOS  CREDITOS  EDUCATIVOS,  OBTENIENDO  EL  GRADO  ACADEMICO   Y   TITULO    CORRESPONDIENTE,    SON LOS:
ORGANIZA PROGRAMAS DE COMPLEMENTACIÓN ACADÉMICA CON EL FIN DE REGULARIZAR LA SITUACIÓN ACADEMICA DEL PERSONAL POLICIAL, ES LA:
ES LA ENCARGADA DE PROMOVER LA EVALUACIÓN, ACREDITACIÓN Y  CERTIFICACIÓN DE LA CALIDAD EDUCATIVA DE  SUS PROGRAMAS ACADÉMICOS Y GESTIÓN   INSTITUCIONAL,   CUYA   EJECUCIÓN   ES REALIZADA POR LAS DEMAS ESCUELAS, SE REFIERE ALA:
ES  EL PROCEDIMIENTO QUE REALIZA LA ESCUELA  NACIONAL   DE   FORMACION  PROFESIONAL  POLICIAL  Y SUS  RESPECTIVAS  ESCUELAS  COMO  UNIDADES  ACADEMICAS   PARA    ESTABLECER  EQUIVALENCIAS  SOBRE LA BASE DE LOS OBJETIVOS, CONTENIDOS Y CREDITOS DE LAS ASIGNATURAS COMPRENDIDAS   EN   LOS PLANES  DE ESTUDIO VIGENTES DE SIMILAR NATURALEZA DE   LAS  INSTITUCIONES  EDUCATIVAS, NACIONALES O EXTRANJERAS, DE NIVEL SUPERIOR DEL SISTEMA EDUCATIVO, SE REFIERE A:
CUAL ES LA ENTIDAD ENCARGADA  DE   REVALIDAR  LOS  GRADOS  ACADEMICOS  Y  TITULOS  PROFESIONALES DEL EXTRANJERO, EN LAS MATERIAS DE SU COMPETENCIA, PREVIO PRONUNCIAMIENTO DEL CONSEJO ACADEMICO:
CONSTITUYEN LA PRIMERA INSTANCIA DE LOS PROCESOS SOMETIDOS A SU   CONOCIMIENTO   Y COMPETENCIA
CONSTITUYEN LA SEGUNDA INSTANCIA DE LOS PROCESOS SOMETIDOS A SU CONOCIMIENTO Y COMPETENCIA
LAS INFRACCIONES SEGÚN SU GRAVEDAD SE CLASIFICAN EN:
LAS SANCIONES DE ACUERDO A LA GRAVEDAD DE LA INFRACCIÓN SE CLASIFICAN EN:
UN ESTUDIANTE PNP DE PREGRADO DE LA ESCUELA NACIONAL DE FORMACIÓN PROFESIONAL POLICIAL, POR INFRACCIÓN MUY GRAVE SERA EXPULSADO SI:
UN ESTUDIANTE PNP DE PREGRADO DE LA ESCUELA NACIONAL DE FORMACIÓN PROFESIONAL POLICIAL, POR INFRACCIÓN MUY GRAVE SERA EXPULSADO SI:
UN ESTUDIANTE PNP DE PREGRADO DE LA ESCUELA NACIONAL DE FORMACIÓN PROFESIONAL POLICIAL, POR INFRACCIÓN MUY GRAVE SERA EXPULSADO SI:
UN ESTUDIANTE PNP DE PREGRADO DE LA ESCUELA NACIONAL DE FORMACIÓN PROFESIONAL POLICIAL, POR INFRACCIÓN MUY GRAVE SERA EXPULSADO SI:
ES UNA CAUSAL DESEPARACION:
ES UNA CAUSAL DEBAJA:
TODAS LAS ESCUELA O UNIDADES ACADÉMICAS DE LA POLICÍA NACIONAL DEL PERÚ DEPENDEN DE:
ES EL CONJUNTO DE PRINCIPIOS, NORMAS, PROCESOS Y CONDICIONES QUE REGULAN LA CAPTACIÓN, EL INGRESO, LA INCORPORACIÓN, PERMANENCIA, DESENVOLVIMIENTO Y TÉRMINO DE LA ACTIVIDAD PROFESIONAL Y TÉCNICA DEL PERSONAL
SON COMPETENCIAS INSTITUCIONALES
ES EL RESPONSABLE DEL SOPORTE TECNOLÓGICO DEL SISTEMA INTEGRADO DE GESTION DE LA CARRERA:
SE ORGANIZA EN NIVELES DE OFICIALES Y SUBOFICIALES, CONTANDO CADA UNO DE ELLOS CON SUS CATEGORÍAS, JERARQUÍAS Y GRADOS:
LOS PROCESOS TÉCNICOS DE LA CARRERA DEL PERSONAL POLICIAL SON LOS SIGUIENTES:
LAS ESPECIALIDADES FUNCIONALES SON LAS RAMAS O CAMPOS OCUPACIONALES DE LA POLICIA NACIONAL DEL PERÚ RELACIONADAS CON LA FINALIDAD FUNDAMENTAL SEÑALADA EN EL ARTICULO 166 DE LA CONSTITUCIÓN POLITICA DEL PERÚ, Y QUE REQUIEREN DE ESTUDIOS Y ENTRENAMIENTOS POLICIALES DURANTE TODA LA CARRERA:
ADMISIÓN Y MATRICULA PARA LA ASIMILACIÓN DE OFICIALES Y SUBOFICIALES DE SERVICIOS: A PROPUESTA DE LA DIRECCIÓN DE RECURSOS HUMANOS Y DE ACUERDO AL PLAN ESTRATÉGICO, APROBARÁ EL NUMERO DE VACANTES DEL PERSONAL PROFESIONAL Y TECNICO:
ESTÁ A CARGO DE LA DIRECCIÓN EJECUTIVA DE EDUCACIÓN Y DOCTRINA. ES DE CARÁCTER OBLIGATORIO Y TIENE POR FINALIDAD FACILITAR LA INTEGRACIÓN DEL PERSONAL ASIMILADO A LA MISTICA, USOS, COSTUMBRES, NORMAS, PRINCIPIOS, VALORES Y DOCTRINA DE LA POLICIA NACIONAL DEL PERÚ:
A TRAVÉS DE LA DIRECCIÓN NACIONAL DE GESTIÓN INSTITUCIONAL PROPONE A LA DIRECCIÓN GENERAL DE LA POLICIA NACIONAL DEL PERÚ LAS NECESIDADES DE INCORPORACIÓN DE PROFESIONALES UNIVERSITARIOS, TÉCNICOS Y PERSONAS:
ES LA CONDICIÓN LABORAL DEL PERSONAL DEL LA POLICIA NACIONAL DEL PERÚ EN SITUACIÓN DE ACTIVIDAD, EN FUNCIÓN A SU CATEGORÍA Y GRADO:
ES EL INSTRUMENTO DE REGISTRO DE CARÁCTER OFICIAL DE LA PRESENCIA FISICA Y EL EJERCICIO DEL EMPLEO Y CARGO DEL PERSONAL EN SITUACIÓN DE ACTIVIDAD:
LA ASIGNACIÓN Y REASIGNACIÓN DE OFICIALES GENERALES, SUPERIORES Y SUBALTERNOS, SE APRUEBA POR:
EN LOS LUGARES DONDE NO SE LOGRE CUBRIR EL CARGO DE COMISARIOS CON OFICIALES DE ARMAS, SE ASIGNARÁN:
MEDIANTE RESOLUCIÓN DIRECTORAL DE LA COMANDANCIA GENERAL SE DESIGNARÁ A LOS INTEGRANTES DE LAS JUNTAS PARA LA ASIGNACIÓN DE CARGOS DE OFICIALES DE ARMAS Y DE SERVICIOS, LAS MISMAS QUE ENTRARÁN EN FUNCIONAMIENTO EN EL MES DE:
LOS SUBOFICIALES DE SERVICIOS SERÁN ASIGNADOS EN CARGOS QUE TENGAN RELACIÓN DIRECTA CON LA ESPECIALIDAD O CARRERA TÉCNICA, CON LA QUE FUERON DADOS DE ALTA. EN NINGÚN CASO PUEDEN COMANDAR:
NO PODRÁN PRESTAR SERVICIOS EN UNA MISMA UNIDAD O SUBUNIDAD POLICIAL A ÓRDENES DIRECTAS DEL MISMO SUPERIOR JERÁRQUICO, EL PERSONAL QUE TENGA ENTRE SÍ PARENTESCO:
LOS OFICIALES DE SERVICIOS SERÁN ASIGNADOS, REASIGNADOS O DESTACADOS EN CARGOS QUE TENGAN RELACIÓN DIRECTA CON LA PROFESIÓN CON LA QUE FUERON DADOS DE ALTA. EL TIEMPO DE PERMANENCIA ESTARÁ SUJETO A:
LA EVALUACIÓN DE DESEMPEÑO ALCANZA A TODO EL PERSONAL DE LA POLICÍA NACIONAL DEL PERÚ EN SITUACIÓN DE:
SE CONSIDERA “SERVICIOS MERITORIOS”, A LOS AÑOS DE SERVICIOS REALES, EFECTIVOS E ININTERRUMPIDOS QUE EL PERSONAL HAYA PRESTADO EFICIENTEMENTE EN LA:
LOS CONSEJOS DE INVESTIGACIÓN ESTARÁN CONSTITUIDOS POR:
LOS CONSEJOS DE INVESTIGACIÓN TIENEN JURISDICCIÓN A NIVEL:
EL ASCENSO TIENE POR FINALIDAD PROMOVER AL PERSONAL AL GRADO INMEDIATO SUPERIOR, EN CONSIDERACIÓN A SUS:
LOS OFICIALES DE SERVICIOS DE LA POLICÍA NACIONAL DEL PERÚ, QUE OBTUVIERON LA EFECTIVIDAD COMO PROFESIONALES TITULADOS EN DERECHO O MEDICINA HUMANA, PODRÁN ASCENDER HASTA EL GRADO DE:
LOS DEMÉRITOS CONTEMPLADOS EN LA TABLA DE INFRACCIONES Y SANCIONES GRAVES Y MUY GRAVES, DEL DECRETO LEGISLATIVO Nº 1150, LEY DEL RÉGIMEN DISCIPLINARIO DE LA POLICÍA NACIONAL DEL PERÚ, SE PONDERAN HASTA:
SITUACIÓN DE DISPONIBILIDAD, QUE ES LA CONDICIÓN TRANSITORIA EN QUE SE ENCUENTRA EL PERSONAL DE LA POLICÍA NACIONAL DEL PERÚ, FUERA DEL SERVICIO, POR UN PERÍODO MÁXIMO DE:
LA CALIFICACIÓN DE LAS CIRCUNSTANCIAS DEL SERVICIO QUE SE REFIERE EL ARTÍCULO 63 DE LA LEY, ES EVALUADA Y DETERMINADA POR:
EL DISFRUTE DE LAS VACACIONES ES DE CARÁCTER OBLIGATORIO E IRRENUNCIABLE Y NO PUEDE SER SUSTITUIDO POR:
ES EL PERÍODO DE DESCANSO REMUNERADO QUE SE CONCEDE AL PERSONAL EN ACTIVIDAD:
ES LA ATRIBUCIÓN QUE SE CONFIERE AL JEFE DE LA UNIDAD PARA AUTORIZAR AL PERSONAL A AUSENTARSE DEL SERVICIO POR RAZONES DEBIDAMENTE MOTIVADAS Y JUSTIFICADAS:
EL PERSONAL PASA A LA SITUACIÓN DE DISPONIBILIDAD POR LA CAUSAL DE MEDIDA DISCIPLINARIA EN LOS SIGUIENTES CASOS:
EL PERSONAL POLICIAL PASA A LA SITUACIÓN DE DISPONIBILIDAD POR SENTENCIA JUDICIAL CONDENATORIA, CUANDO:
LOS CONSEJOS DE CALIFICACIÓN SON NOMBRADOS MEDIANTE::
PASA A LA SITUACIÓN DE DISPONIBILIDAD POR ENFERMEDAD O LESIÓN GRAVE:
EL PERSONAL PASA AL RETIRO POR LIMITE DE PERMANENCIA EN LA SITUACIÓN DE DISPONIBILIDAD , CUANDO:
EL PERSONAL PASA A LA SITUACIÓN DE RETIRO POR MEDIDA DISCIPLINARIA EN LOS SIGUIENTES CASOS:
LA MACRO REGIÓN POLICIAL DE LAMBAYEQUE, ESTA CONFORMADA POR LAS REGIONES POLICIALES DE:
LA DIRECCIÓN CONTRA EL TERRORISMO PARA EL CUMPLIMIENTO DE SUS FUNCIONES CUENTA CON UNIDADES ORGÁNICAS ESPECIALIZADAS; CUÁL NO CORRESPONDE:
LA MACRO REGIÓN POLICIAL LA LIBERTAD, ESTA CONFORMADA POR LAS REGIONES POLICIALES DE:
LA DIRECCIÓN CONTRA EL TERRORISMO PARA EL CUMPLIMIENTO DE SUS FUNCIONES CUENTA CON UNIDADES ORGÁNICAS ESPECIALIZADAS; CUÁL NO CORRESPONDE:
ES EL ÓRGANO ESPECIALIZADO, DE CARÁCTER TÉCNICO Y SISTÉMICO, NORMATIVO Y OPERATIVO; RESPONSABLE DE  PREVENIR,  INVESTIGAR,  COMBATIR  Y  DENUNCIAR  EL  DELITO  DE TERRORISMO, COMETIDO POR ELEMENTOS O GRUPOS NACIONALES O EXTRANJEROS EN NUESTRO PAÍS
LA MACRO REGIÓN POLICIAL PIURA, ESTA CONFORMADA POR LAS REGIONES POLICIALES DE:
NO ES UNA FUNCIÓN DE LA DIRECCIÓN CONTRA EL TERRORISMO:
NO ES UNA FUNCIÓN DE LA DIVISIÓN DE INTELIGENCIA ANTIDROGAS
ES UNA UNIDAD ORGÁNICA DESCONCENTRADA A NIVEL NACIONAL, DE CARÁCTER TÉCNICO, OPERATIVO Y ESPECIALIZADO;  RESPONSABLE  EL   PLANEAMIENTO,   ORGANIZACIÓN,	COORDINACIÓN, EJECUCIÓN, CONTROL Y SUPERVISIÓN DE LAS ACTIVIDADES Y OPERACIONES POLICIALES ANTIDROGAS DEL NIVEL OPERACIONAL Y TÁCTICO DE INTERDICCIÓN TERRESTRE, AÉREA, MARÍTIMA, LACUSTRE Y FLUVIAL
REALIZAR LA GESTIÓN ADMINISTRATIVA Y DOCUMENTARIA DE LA DIRECCIÓN NACIONAL DE ORDEN Y SEGURIDAD DE LA POLICÍA NACIONAL DEL PERÚ; ES UNA FUNCIÓN DE:
NO ES UNA FUNCIÓN DE LA DIVISIÓN DE INVESTIGACIÓN CONTRA EL DESVÍO DE INSUMOS QUÍMICOS:
ES LA UNIDAD ORGÁNICA ESPECIALIZADA Y OPERATIVA, RESPONSABLE DE PRODUCIR INTELIGENCIA Y CONTRAINTELIGENCIA POLICIAL EN MATERIA DE DELITOS CONTRA EL TRÁFICO ILÍCITO DE DROGAS Y DELITOS CONEXOS A NIVEL NACIONAL, PUDIENDO CONTAR CON LA COOPERACIÓN Y APOYO DE AGENCIAS INTERNACIONALES, DE CONFORMIDAD CON LOS LINEAMIENTOS DE LA DIRECCIÓN DE INTELIGENCIA DE LA POLICÍA NACIONAL DEL PERÚ
CUMPLEN FUNCIONES ESPECÍFICAS EN UNA O MAS REGIONES POLICIALES Y/O FRENTES POLICIALES, DONDE ACTUANDO EN REPRESENTACIÓN Y POR DELEGACIÓN EJERCEN MANDO Y COMANDO:
A PROPUESTA DEL DIRECTOR GENERAL DE LA POLICÍA NACIONAL DEL PERÚ, MEDIANTE QUE NORMA LEGAL, SON CREADAS, FUSIONADAS O SUPRIMIDAS, LAS MACRO REGIONES POLICIALES:
ES LA UNIDAD ORGÁNICA DE CARÁCTER TÉCNICO, OPERATIVO Y ESPECIALIZADO, RESPONSABLE DE LA PREVENCIÓN, INVESTIGACIÓN Y EL COMBATE DEL TRÁFICO ILÍCITO DE INSUMOS QUÍMICOS O PRODUCTOS FISCALIZADOS Y EL DESVÍO DE SUSTANCIAS QUÍMICAS CONTROLADAS O NO CONTROLADAS DESTINADAS A LA PRODUCCIÓN, EXTRACCIÓN O PREPARACIÓN ILÍCITA DE DROGAS, MEDIANTE EL CONTROL Y FISCALIZACIÓN EN EL MARCO DE LA NORMATIVA LEGAL VIGENTE
NO ES UNA FUNCIÓN DE LA DIVISIÓN DE PREVENCIÓN CONTRA EL TRÁFICO ILÍCITO DE DROGAS:
DIRIGIR Y SUPERVISAR ACTIVIDADES QUE PERMITAN ORIENTAR Y APOYAR A LOS TURISTAS EXTRANJEROS QUE REQUIERAN PONERSE EN CONTACTO CON LOS CONSULADOS, EMBAJADAS Y REPRESENTACIONES DIPLOMÁTICAS DE SU PAÍS DE ORIGEN; ES UN FUNCIÓN DE:
PLANEAR, ORGANIZAR, DIRIGIR, EJECUTAR, COORDINAR, CONTROLAR Y SUPERVISAR A NIVEL NACIONAL LAS ACTIVIDADES Y OPERACIONES POLICIALES DE PROTECCIÓN Y SEGURIDAD DE LOS BIENES PATRIMONIALES, HISTÓRICOS, CULTURALES Y TURÍSTICOS DE LA NACIÓN; ES UNA FUNCIÓN DE
ES LA UNIDAD ORGÁNICA DE CARÁCTER TÉCNICO Y ESPECIALIZADO, RESPONSABLE DE PLANIFICAR, ORGANIZAR, DIRIGIR, EJECUTAR, COORDINAR, CONTROLAR Y SUPERVISAR LAS ACTIVIDADES RELACIONADAS CON LA PREVENCIÓN DEL DELITO DE TRÁFICO ILÍCITO DE DROGAS EN COORDINACIÓN CON ORGANISMOS PÚBLICOS Y PRIVADOS, NACIONALES O EXTRANJEROS, DESARROLLANDO ADEMÁS PROGRAMAS DE PROYECCIÓN SOCIAL PARA PREVENIR EL USO INDEBIDO Y ABUSO DE DROGAS
NO ES UNA FUNCIÓN DE LA DIVISIÓN PORTUARIA ANTIDROGAS LOGÍSTICOS DE EXPORTACIÓN MARÍTIMA Y OTRAS, PARA EL CUMPLIMIENTO DE LAS FUNCIONES ASIGNADAS EN LA LUCHA CONTRA EL TRÁFICO ILÍCITO DE DROGAS
ES RESPONSABLE DE  PLANEAR,  ORGANIZAR, DIRIGIR, EJECUTAR,  COORDINAR, CONTROLAR Y  SUPERVISAR LAS ACTIVIDADES Y OPERACIONES POLICIALES DE ORIENTACIÓN, SEGURIDAD, PROTECCIÓN, PREVENCIÓN, INVESTIGACIÓN Y DENUNCIA DE FALTAS Y DELITOS EN AGRAVIO DE TURITAS EXTRANJEROS Y SUS BIENES; CORRESPONDE A:
ES LA UNIDAD ORGÁNICA DE CARÁCTER TÉCNICO, OPERATIVO Y ESPECIALIZADO; RESPONSABLE DE INVESTIGAR Y DENUNCIAR EN EL ÁMBITO NACIONAL, BAJO LA CONDUCCIÓN JURÍDICA EL FISCAL, A LOS QUE PROMUEVEN, ORGANICEN, FINANCIEN, DIRIJAN, FAVOREZCAN O FACILITEN EL TRÁFICO  Y	EL CONSUMO ILEGAL DE DROGAS TÓXICAS, ESTUPEFACIENTES O SUSTANCIAS PSICOTRÓPICAS, MEDIANTE ACTOS DE CULTIVO, FABRICACIÓN O TRÁFICO, O LAS QUE LO POSEAN CON ESTE ÚLTIMO FIN;  CORRESPONDE A:
INTEGRA LA ESTRUCTURA DE LA DIRECCIÓN DE TRÁNSITO, TRANSPORTE Y SEGURIDAD VIAL
ES RESPONSABLE DE  PLANEAR,  ORGANIZAR, DIRIGIR, EJECUTAR,  COORDINAR, CONTROLAR Y  SUPERVISAR LAS ACTIVIDADES TENDENTES A PROMOVER LA PARTICIPACIÓN ACTIVA Y ORGANIZADA DE LA COMUNIDAD, FORTALECIENDO LAS RELACIONES POLICÍA  - AUTORIDAD - COMUNIDAD; CORRESPONDE	A:
ORIENTAR, EJECUTAR Y SUPERVISAR LAS ACCIONES POLICIALES DE PROTECCIÓN TEMPORAL DE NIÑOS, NIÑAS Y ADOLESCENTES EN ABANDONO E INFRACTORES A LA LEY PENAL; ES UNA FUNCIÓN DE:
ES LA UNIDAD ORGÁNICA DE CARÁCTER TÉCNICO,  OPERATIVO  Y  ESPECIALIZADO;  RESPONSABLE  DE  PREVENIR Y COMBATIR EL TRÁFICO ILÍCITO DE DROGAS EN SUS DIVERSAS MODALIDADES, MEDIANTE ACCIONES DE INTERDICCIÓN PRINCIPALMENTE EN EL ÁMBITO PORTUARIO MARÍTIMO, FLUVIAL, LACUSTRE	Y AEROPORTUARIO, A NIVEL NACIONAL; CORRESPONDE A:
INTEGRA LA ESTRUCTURA DE LA DIRECCIÓN DE SEGURIDAD CIUDADANA
ES RESPONSABLE DE FISCALIZAR EL CUMPLIMIENTO DE LAS NORMAS DE TRÁNSITO POR PARTE DE LOS USUARIOS DE LA INFRAESTRUCTURA VIAL; CORRESPONDE A:
ES EL ÓRGANO ESPECIALIZADO, DE CARÁCTER TÉCNICO Y SISTÉMICO, NORMATIVO Y OPERATIVO;  RESPONSABLE DE PLANEAR, COMANDAR, ORGANIZAR, EJECUTAR, COORDINAR,  CONTROLAR  Y  SUPERVISAR LAS ACTIVIDADES Y OPERACIONES POLICIALES ANTIDROGAS DE MAYOR ENVERGADURA Y COMPLEJIDAD EN LOS CAMPO DE LA PREVENCIÓN, INTELIGENCIA, INVESTIGACIÓN E INTERDICCIÓN PARA COMBATIR EL TRÁFICO ILÍCITO E INSUMOS QUÍMICOS Y PRODUCTOS FISCALIZADOS
INTEGRA LA ESTRUCTURA DE LA DIRECCIÓN DE SEGURIDAD INTEGRAL
INTEGRA LA ESTRUCTURA DE LA DIRECCIÓN DE SEGURIDAD DE INTEGRAL:
ES LA UNIDAD ORGÁNICA ESPECIALIZADA Y OPERATIVA, RESPONSABLE DE PRODUCIR INTELIGENCIA Y CONTRAINTELIGENCIA POLICIAL EN EL ÁMBITO DE SU COMPETENCIA DE LA  DIRECCIÓN  DE  MEDIO  AMBIENTE A NIVEL NACIONAL; CORRESPONDE A:
ES RESPONSABLE DE PLANEAR, ORGANIZAR, CONDUCIR Y COORDINAR, EVALUAR Y SUPERVISAR LAS OPERACIONES POLICIALES RELACIONADAS A LA SEGURIDAD  DE FRONTERAS, SEGURIDAD AEROPORTUARIA, FLUVIAL Y LACUSTRE, SEGURIDAD DE SERVICIOS ESENCIALES Y ENTIDADES PÚBLICAS, SEGURIDAD DE EMBAJADAS, Y RESIDENCIAS DIPLOMÁTICAS; Y SUBSIDIARIAMENTE LA SEGURIDAD DE LOS PENALES; CORRESPONDE A:
NO INTEGRA LA ESTRUCTURA DE LA DIRECCIÓN DE OPERACIONES POLICIALES:
ES RESPONSABLE DE COORDINAR Y ESTABLECER DE MANERA ARTICULADA LAS LÍNEAS DE ACCIÓN CONJUNTA, COMPLEMENTARIAS Y SUBSIDIARIAS EN APOYO A LAS MACRO REGIONES POLICIALES, REGIONES Y FRENTES POLICIALES:
RESPECTO A LOS BIENES JURÍDICOS PROTEGIDOS DE LA PNP, INDICAR LO QUE NO CORRESPONDE:
RESPECTO AL CONDUCTO REGULAR, CUMPLIMIENTO DE ORDENES Y PRELACION, EN LO RELACIONADO AL CUMPLIMIENTO DE LAS ORDENES, ESTA NO DEBEN SER:
RESPECTO A LA NOTA ANUAL DE DISCIPLINA, INDIQUE LA ALTERNATIVA QUE CORRESPONDA:
SE ENTIENDE POR REINCIDENCIA
SE ENTIENDE POR HABITUALIDAD
RELACIONADO A LOS PROCEDIMIENTOS ADMINISTRATIVOS DISCIPLINARIOS POR INFRACCIONES INSTANTÁNEAS POR INFRACCIONES LEVES PRESCRIBE EN:
LA FACULTAD PARA EL INICIO DE LOS PROCEDIMIENTOS ADMINISTRATIVOS DISCIPLINARIOS POR INFRACCIONES INSTANTÁNEAS POR INFRACCIONES MUY GRAVES PRESCRIBE A LOS?:
LA FACULTAD PARA EL INICIO DE LOS PROCEDIMIENTOS ADMINISTRATIVOS DISCIPLINARIOS POR INFRACCIONES INSTANTANEAS POR INFRACCIONES GRAVES PRESCRIBE A LOS?:
EL SISTEMA DISCIPLINARIO POLICIAL ES EL CONJUNTO DE ÓRGANOS DEL?:
FUNCIONES DE LA OFICINA DE ASUNTOS INTERNOS?
REQUISITOS PARA SER MIEMBRO DEL TRIBUNAL DE DISCIPLINA POLICIAL
PERIODO DE DESIGNACIÓN DE LOS VOCALES DEL TRIBUNAL DE DISCIPLINA POLICIAL:
DE LOS ACTOS INIMPUGNABLES:
LAS NOTIFICACIONES. REGLAS PARA LAS NOTIFICACIONES SON VALIDAS SI SE REALIZAN EN:
ATRIBUCIONES DE LAS SALAS DEL TRIBUNAL DE DISCIPLINA POLICIAL:
CRITERIOS PARA DETERMINAR LA COMPLEJIDAD Y AMPLIACIÓN DE PLAZOS DE UN PROCEDIMIENTO ADMINISTRATIVOS DISCIPLINARIO. INDICAR LA ALTERNATIVA CORRECTA
REQUISITOS PARA SER MIEMBRO DEL TRIBUNAL DE DISCIPLINA POLICIAL
INHIBICIÓN DE LOS MIEMBROS DE LOS ÓRGANOS DEL SISTEMA DISCIPLINARIO POLICIAL. LOS INTEGRANTES DE LOS ÓRGANOS DEL SISTEMA DISCIPLINARIO POLICIAL TIENEN LA OBLIGACIÓN DE INHIBIRSE:
RECUSACIÓN DE LOS MIEMBROS DE LOS ÓRGANOS DEL SISTEMA DISCIPLINARIO POLICIAL. ANTE LA AUSENCIA DE INHIBICIÓN DE LOS MIEMBROS DE LOS ÓRGANOS DEL SISTEMA DISCIPLINARIO POLICIAL, EL INVESTIGADO PUEDE INTERPONER LA SOLICITUD DE RECUSACIÓN, LA QUE ES RESUELTA POR EL SUPERIOR JERÁRQUICO EN UN PLAZO:
SUPLENCIA DEL INSPECTOR MACRO REGIONAL, INSPECTOR DESCENTRALIZADO O JEFE DE OFICINA DE DISCIPLINA. EL SUPLENTE ES NOMBRADO POR:
FORMULACIÓN DE DENUNCIAS. LAS DENUNCIAS RECIBIDAS QUE IMPLIQUEN EL INICIO DE UN PROCEDIMIENTO ADMINISTRATIVO DISCIPLINARIO CONTRA EL PERSONAL DE LA POLICÍA NACIONAL DEL PERÚ POR INFRACCIONES AL RÉGIMEN DISCIPLINARIO SE PRESENTAN ANTE: (INDIQUE LA QUE NO CORRESPONDE).
SOBRE LAS DENUNCIAS ANÓNIMAS. TODA DENUNCIA ANÓNIMA DEBE SER:
PLAZO PARA APELAR SANCIONES POR INFRACCIONES LEVES. (INDIQUE LA ALTERNATIVA CORRECTA)
COMPETENCIA DE LA OFICINA DE DISCIPLINA. LA OFICINA DE DISCIPLINA TIENE COMPETENCIA PARA INVESTIGAR INFRACCIONES GRAVES Y MUY GRAVES COMETIDAS POR PERSONAL POLICIAL HASTA EL GRADO DE:
EMISIÓN DEL INFORME ADMINISTRATIVO DISCIPLINARIO. EL INFORME ADMINISTRATIVO DISCIPLINARIO DEBE CONTENER LO SIGUIENTE: (UNA DE LAS ALTERNATIVAS NO CORRESPONDE)
DE LAS MEDIDAS PREVENTIVAS. LAS MEDIDAS PREVENTIVAS SON DISPOSICIONES ADMINISTRATIVAS DE CARÁCTER PROVISIONAL QUE SE IMPONEN ANTE LA PRESUNTA COMISIÓN DE INFRACCIONES MUY GRAVES. ESTAS PUEDEN SER: (SOLO UNA ES CORRECTA)
PROCEDIMIENTOS ESPECIALES. - DE LAS MEDIDAS PREVENTIVAS. ESTA MEDIDA PREVENTIVA SE PRODUCE CUANDO EL INVESTIGADO SE ENCUENTRA PRIVADO DE SU LIBERTAD POR MANDATO DEL ÓRGANO JURISDICCIONAL SIN SENTENCIA CONDENATORIA FIRME.
PROCEDIMIENTOS ESPECIALES. - DE LAS MEDIDAS PREVENTIVAS. NO AFECTA LA REMUNERACIÓN CONSOLIDADA QUE EL INVESTIGADO TIENE DERECHO A PERCIBIR.
PROCEDIMIENTOS ESPECIALES. - DE LAS MEDIDAS PREVENTIVAS. ES UNA MEDIDA PREVENTIVA QUE SOLAMENTE PUEDE SER IMPUESTA EN LOS PROCEDIMIENTOS ADMINISTRATIVOS DISCIPLINARIOS SUMARIOS O EN LOS CASOS DONDE SE INVESTIGAN INFRACCIONES MUY GRAVES QUE SE SANCIONAN CON PASE A LA SITUACIÓN DE RETIRO.
EFECTOS DE LA MEDIDA PREVENTIVA DE SUSPENSIÓN TEMPORAL DEL SERVICIO. (…) DICHO PERSONAL QUEDA PROHIBIDO DE USAR EL UNIFORME POLICIAL, NO EJERCE NINGÚN CARGO EN LA INSTITUCIÓN, NO SE LE ASIGNA ARMAMENTO DEL ESTADO, NO SE LE ASIGNA TICKET DE RACIÓN ORGÁNICA ÚNICA DIARIA (ROUD), Y PERCIBE:
DEL PROCEDIMIENTO ADMINISTRATIVO DISCIPLINARIO SUMARIO. LA DISPOSICIÓN DE INICIO DE UN PROCEDIMIENTO ADMINISTRATIVO DISCIPLINARIO SUMARIO SE DA EN EL SIGUIENTE CASO: FLAGRANCIA, ENTENDIÉNDOSE ESTA CUANDO EL PERSONAL POLICIAL: (SOLO UNA ES CORRECTA)
DEL PROCEDIMIENTO ADMINISTRATIVO DISCIPLINARIO SUMARIO. LA DISPOSICIÓN DE INICIO DE UN PROCEDIMIENTO ADMINISTRATIVO DISCIPLINARIO SUMARIO SE DA EN EL SIGUIENTE CASO: CONFESIÓN CORROBORADA, ENTENDIÉNDOSE ESTA COMO LA ACEPTACIÓN CLARA DE LA RESPONSABILIDAD POR LA INFRACCIÓN (	) QUE SE LE IMPUTA
DEL PROCEDIMIENTO ADMINISTRATIVO DISCIPLINARIO SUMARIO. - DESCARGOS DEL INVESTIGADO. EL INVESTIGADO CUENTA CON ( ) PARA PRESENTAR POR ESCRITO SUS DESCARGOS AL ÓRGANO DE INVESTIGACIÓN.
DE LA EJECUCIÓN, REGISTRO Y CODIFICACIÓN DE RESOLUCIONES. - EJECUCIÓN DE RESOLUCIONES: LAS RESOLUCIONES CONSENTIDAS Y FIRMES SON DE EJECUCIÓN ( )
DE LA EJECUCIÓN, REGISTRO Y CODIFICACIÓN DE RESOLUCIONES. - EFECTOS DE LA SANCIÓN GRAVE Y MUY GRAVE EN EL DESEMPEÑO DEL CARGO: EL PERSONAL DE LA POLICÍA NACIONAL DEL PERÚ SANCIONADO CON RESOLUCIÓN FIRME POR LA COMISIÓN DE INFRACCIÓN GRAVE O MUY GRAVE QUE AFECTE LA FUNCIÓN QUE VENÍA DESEMPEÑANDO, NO PUEDE CONTINUAR NI VOLVER A SER ASIGNADO EN EL CARGO QUE OCUPABA AL MOMENTO DE COMETER LA INFRACCIÓN O EN FUNCIONES ANÁLOGAS EN OTRA UNIDAD, POR UN PERÍODO DE (	)