GARANTIZAR EL SECRETO DE LAS INFORMACIONES
GUARDAR EL SECRETO PROFESIONAL|1|C
GARANTIZAR LA LIBERTAD DE INFORMACIÓN
PRESERVAR LA RESERVA DE SUS CONVICCIONES
INVOCAR EL SECRETO A LA LIBERTAD DE CONCIENCIA Y DE RELIGIÓN

EL EMPLEO Y COMERCIALIZACIÓN DE FÁRMACOS|2
LA COMERCIALIZACIÓN DE PRODUCTOS NOCIVOS|2
EL USO DE LOS TÓXICOS SOCIALES|2|C
LA COMERCIALIZACIÓN DETÓXICOS|2
EL USO DE FÁRMACOS DEPENDIENTES|2

DEBERES PRIMORDIALES DEL ESTADO|3
LA POLÍTICA GENERAL DEL GOBIERNO|3
OBLIGATORIOS|3|C
ACTIVIDAD DISCRECIONAL DEL ESTADO|3
FACULTATIVOS|3

PUEDE SUPERAR DICHO MÁXIMO|4
PUEDE SUPERAR DICHO MÁXIMO CON ANUENCIA DEL TRABAJADOR|4
PUEDE SUPERAR POR DISPOSICIÓN EXPRESA DEL EMPLEADOR|4
ESTÁ EN RELACIÓN A LAS CONDICIONES LABORALES|4
NO PUEDEN SUPERAR DICHO MÁXIMO |4|C

SESENTAAÑOS|5|
SETENTAAÑOS|5|C
SETENTA Y CINCO AÑOS|5|
SESENTA Y CINCO|5|
OCHENTA AÑOS |5|

LA REFORMA TOTAL O PARCIAL DE LA CONSTITUCIÓN|6|
LA APROBACIÓN DE NORMAS CON RANGO DE LEY|6|
LAS ORDENANZAS MUNICIPALES|6|
LAS MATERIAS RELATIVAS AL PROCESO DE DESCENTRALIZACIÓN|6|
LA REFORMA TOTAL O PARCIAL DE UN DECRETO DE URGENCIA|6|C

POR RESOLUCIÓN JUDICIAL DE INTERDICCIÓN|7|C
POR SENTENCIA CON INHABILITACIÓN DE DERECHOS Y DEBERES|7|
POR RENUNCIA VOLUNTARIA Y EXPRESA A LA CIUDADANÍA|7|
POR LA EMISIÓN DE NORMA CON RANGO DE LEY|7|
POR SENTENCIA ABSOLUTORIA|7|

DEL PODER JUDICIAL|8
DEL MINISTERIO DE RELACIONES EXTERIORES|8
DEL MINISTERIO DE JUSTICIA|8
DE LA CORTE SUPREMA|8|C
DEL JUZGADO PENAL CORRESPONDIENTE|8

LOS MIEMBROS DEL PODER EJECUTIVO INCLUYENDO AL PRESIDENTE DE LA REPÚBLICA|9|
LOS MIEMBROS DE LAS FUERZAS ARMADAS Y DE LA POLICÍA NACIONAL|9|C
LOS MIEMBROS DEL PODER LEGISLATIVO|9|
LOS MIEMBROS DEL TRIBUNAL CONSTITUCIONAL|9|
LOS MIEMBROS DEL PODER JUDICIAL|9|

DEMOCRÁTICA|10|
SOCIAL|10|
INDEPENDIENTE|10|
SOBERANA|10|
AUTÓNOMA|10|C

NACIONAL|11|
REGIONAL|11|
LATINOAMERICANO|11|C
INTERNACIONAL|11|
TRASNACIONAL|11|

MOTÍN O SEDICIÓN|12|C
REBELIÓN O SEDICIÓN|12|
REBELIÓN O INSURRECCIÓN|12|
MOTÍN O INSURRECCIÓN|12|
REBELIÓN O DESACATO|12|

GASTOS JUDICIALES|13|C
GASTOS NOTARIALES|13|
TRIBUTOS|13|
GASTOS BANCARIOS|13|
GASTOS FINANCIEROS|13|

EL MINISTERIO DE RELACIONES EXTERIORES|14|
EL CONSULADO PERUANO|14|
LA SUPERINTENDENCIA NACIONAL DE MIGRACIONES|14|
AUTORIDAD JUDICIAL Y/O ADMINISTRATIVA COMPETENTE|14|
AUTORIDAD PERUANA|14|C

A LA LIBERTAD DE OPINIÓN Y EXPRESIÓN|15|
A LA LIBERTAD Y LA SEGURIDAD PERSONALES|15|C
A LA LIBERTAD DE CONCIENCIA Y DE RELIGIÓN|15|
A LA IGUALDAD ANTE LA LEY|15|
AL SECRETO Y LA INVIOLABILIDAD DE SUS COMUNICACIONES Y DOCUMENTOS PRIVADOS |15|

TREINTA DÍAS|16|
CUARENTA Y CINCO DÍAS|16|
SETENTA DÍAS|16|
SESENTA DÍAS|16|C
NOVENTA DÍAS|16|

EL PRESIDENTE DEL COMANDO CONJUNTO DE LAS FUERZAS ARMADAS|17|
EL COMANDANTE GENERAL DE LA POLICÍA NACIONAL DEL PERÚ|17|
EL PRESIDENTE DE LA REPÚBLICA|17|C
EL MINISTRO DE DEFENSA Y EL MINISTRO DEL INTERIOR|17|
EL DECRETO DE EMERGENCIA|17|

CATÁSTROFE|18|
PERTURBACIÓN DE LA PAZ|18|
PERTURBACIÓN DEL ORDEN INTERNO|18|
GRAVES CIRCUNSTANCIAS QUE AFECTAN LA VIDA Y LA NACIÓN|18|
GUERRA CIVIL|18|C

CUARENTA Y CINCO DÍAS|19|C
TREINTA DÍAS|19|
SESENTA DÍAS|19|
CUARENTA DÍAS|19|
NOVENTA DÍAS|19|

ES LIMITADO A LA DISPOSICIONES DEL COMANDO POLÍTICO MILITAR|20|
NO SE RESTRINGE O SUSPENDE|20|C
SE RESTRINGEN DERECHOS FUNDAMENTALES PERO SU EJERCICIO NO SE SUSPENDE|20|
ES LIBRE Y SUJETO A CONTROL|20|
SI SE RESTRINGE Y SUSPENDE|20|

DEL PRESIDENTE DE LA REPÚBLICA|21|
DEL PODER EJECUTIVO|21|
DEL COMANDO CONJUNTO|21|
DEL CONGRESO|21|C
DEL SISTEMA NACIONAL DE DEFENSA|21|

EL CONGRESO|22|
LA LEY DEL SISTEMA NACIONAL DE MOVILIZACIÓN|22|
EL PRESIDENTE DE LA REPÚBLICA|22|
LA LEY|22|C
EL PODER EJECUTIVO|22|

COMANDO RESPECTIVO|23|
PODER CONSTITUCIONAL|23|C
PODER DEL ESTADO|23|
PODER LEGISLATIVO|23|
PRESIDENTE DE LA REPÚBLICA|23|

EL INSTITUTO CORRESPONDIENTE|24|
EL MINISTERIO DE DEFENSA Y DEL INTERIOR RESPECTIVAMENTE|24|
LA LEY|24|
LAS NORMAS Y REGLAMENTOS RESPECTIVOS|24|
EL PODER EJECUTIVO|24|C

LA ACCIÓN DE HÁBEAS CORPUS|25|C
LA ACCIÓN DE AMPARO|25|
LA ACCIÓN DE HÁBEAS DATA|25|
LA ACCIÓN DE INCONSTITUCIONALIDAD|25|
LA ACCIÓN POPULAR|25|

LA ACCIÓN DE INCONSTITUCIONALIDAD|26|
LA ACCIÓN DE HÁBEAS DATA|26|
LA ACCIÓN POPULAR|26|
LA ACCIÓN DE HÁBEAS CORPUS|26|
LA ACCIÓN DE AMPARO|26|C

LA ACCIÓN POPULAR|27|
LA ACCIÓN DE HÁBEAS CORPUS|27|
LA ACCIÓN DE HÁBEAS DATA|27|
LA ACCIÓN DE AMPARO|27|C
LA ACCIÓN DE INCONSTITUCIONALIDAD|27|

LA ACCIÓN DE AMPARO|28|
LA ACCIÓN DE INCONSTITUCIONALIDAD|28|
LA ACCIÓN POPULAR|28|C
LA ACCIÓN DE HÁBEAS DATA|28|
LA ACCIÓN DE HÁBEAS CORPUS |28|

AL MINITERIO PÚBLICO|29|
AL CONGRESO|29|
AL TRIBUNAL CONSTITUCIONAL|29|
AL MINISTERIO DE JUSTICIA|29|
AL JUEZ|29|C

DEL TERCIO DEL NÚMERO LEGAL DE SUS MIEMBROS|30|
DE LOS DOS TERCIOS DEL NÚMERO LEGAL DE SUS MIEMBROS|30|C
DE LOS DOS QUINTOS DEL NÚMERO LEGAL DE SUS MIEMBROS|30|
DE LA MITAD DEL NÚMERO LEGAL DE SUS MIEMBROS|30|
DEL QUINTO DEL NÚMERO LEGAL DE SUS MIEMBROS|30|

EL PRESIDENTE DE LA REPÚBLICA|31|
EL FISCAL DE LA NACIÓN|31|
EL DEFENSOR DEL PUEBLO|31|
LOS COLEGIOS PROFESIONALES, EN MATERIAS DE SU ESPECIALIDAD|31|
EL CONTRALOR GENERAL DE LA REPÚBLICA|31|C

CINCO MIL CIUDADANOS CON FIRMAS COMPROBADAS POR EL JURADO NACIONAL DE ELECCIONES|32|C
DIEZ MIL CIUDADANOS CON FIRMAS COMPROBADAS POR EL JURADO NACIONAL DE ELECCIONES|32|
QUINCE MIL CIUDADANOS CON FIRMAS COMPROBADAS POR EL JURADO NACIONAL DE ELECCIONES|32|
VEINTE MIL CIUDADANOS CON FIRMAS COMPROBADAS POR EL JURADO NACIONAL DE ELECCIONES|32|
VEINTICINCO MIL CIUDADANOS CON FIRMAS COMPROBADAS POR EL JURADO NACIONAL DE ELECCIONES|32|

EL QUINCE POR CIENTO DEL NÚMERO LEGAL DE CONGRESISTAS|33|
EL VEINTE POR CIENTO DEL NÚMERO LEGAL DE CONGRESISTAS|33|
EL VEINTICINCO POR CIENTO DEL NÚMERO LEGAL DE CONGRESISTAS|33|C
CINCUENTA POR CIENTO DEL NÚMERO LEGAL DE CONGRESISTAS|33|
LOS DOS TERCIOS DEL NÚMERO LEGAL DE CONGRESISTAS|33|

CONOCER, EN INSTANCIA ÚNICA, LA ACCIÓN DE AMPARO|34|
CONOCER, EN INSTANCIA ÚNICA, LA ACCIÓN DE HÁBEAS CORPUS|34|
CONOCER, EN INSTANCIA ÚNICA, LA ACCIÓN POPULAR|34|
CONOCER, EN INSTANCIA ÚNICA, LA ACCIÓN DE INCONSTITUCIONALIDAD|34|C
CONOCER, EN INSTANCIA ÚNICA, LA ACCIÓN DE CUMPLIMIENTO|34|

CON DOS AÑOS DE ANTICIPACIÓN|35|
CON UN AÑO DE ANTICIPACIÓN|35|C
CON SEIS MESES DE ANTICIPACIÓN|35|
CON TRES AÑOS DE ANTICIPACIÓN|35|
CON CINCO AÑOS DE ANTICIPACIÓN|35|

NO SE SUSPENDE DURANTE LA VIGENCIA DE LOS REGÍMENES DE EXCEPCIÓN|36|C
SE SUSPENDE DURANTE LA VIGENCIA DE LOS REGÍMENES DE EXCEPCIÓN|36|
SE SUSPENDE EN FORMA PARCIAL DURANTE LA VIGENCIA DE LOS REGÍMENES DE EXCEPCIÓN|36|
SE SUSPENDE EN FORMA TOTAL DURANTE LA VIGENCIA DE LOS REGÍMENES DE EXCEPCIÓN|36|
SÓLO SE SUSPENDE ALGUNOS DERECHOS QUE LA AUTORIDAD JUDICIAL SEÑALA DURANTE LA VIGENCIA DE LOS REGÍMENES DE EXCEPCIÓN|36|

ÓRDEN ECONÓMICO|37|
ÓRDEN SOCIAL|37|
ÓRDEN CONSTITUCIONAL|37|C
INTERESES DE LOS GREMIOS EN CONFLICTO|37|
INTERESES DE SECTORES DE LA POBLACIÓN|37|

EL DEFENSOR DEL PUEBLO, CONFORME A LEY|38|
EL FISCAL DE LA NACIÓN, CONFORME A LEY|38|
EL PODER JUDICIAL, CONFORME A LEY|38|
EL CONGRESO DE LA REPÚBLICA, CONFORME A LEY|38|
LOS PROCURADORES PÚBLICOS, CONFORME A LEY|38|C

DECRETO DE URGENCIA|39|
LA LEY|39|C
NORMAS DE CARÁCTER ADMINISTRATIVO|39|
SENTENCIAS DEL TRIBUNAL CONSTITUCIONAL|39|
NORMAS LABORALES|39|

AL TOMAR POSESIÓN DE SUS CARGOS, ÚNICAMENTE|40|
AL TOMAR POSESIÓN DE SUS CARGOS Y AL CESAR EN LOS MISMOS, ÚNICAMENTE|40|
AL TOMAR POSESIÓN DE SUS CARGOS, DURANTE SU EJERCICIO Y AL CESAR EN LOS MISMOS|40|C
DURANTE SU EJERCICIO Y AL CESAR EN LOS MISMOS|40|
AL CESAR DE SUS CARGOS, ÚNICAMENTE|40|

UNIDAD DE COMANDO|41|
UNIDAD DE LA FUNCIÓN POLICIAL|41|C
UNIDAD DE DIRECCIÓN|41|
CENTRALIZACIÓN DE LA FUNCIÓN|41|
LEGALIDAD|41|

UNIDAD DE LA FUNCIÓN POLICIAL|42|
CENTRALIZACIÓN DE LAFUNCIÓN|42|
UNIDAD DE COMANDO|42|C
LEGALIDAD|42|
UNIDAD DE DIRECCIÓN|42|

HONESTIDAD|43|
INTEGRIDAD|43|
JUSTICIA|43|
TRANSPARENCIA|43|
HONOR|43|C

INTEGRIDAD|44|C
HONOR|44|
DISCIPLINA|44|
TRANSPARENCIA|44|
VOCACIÓN|44|

UNA COMPETENCIA|45|
UNA FUNCIÓN|45|C
UNA ATRIBUCIÓN|45|
UNA FACULTAD|45|
UNA OBLIGACIÓN|45|

UNA OBLIGACIÓN|46|
UNA FACULTAD|46|
UNA FUNCIÓN|46|
UNA ATRIBUCIÓN|46|C
UNA COMPETENCIA|46|

UNA OBLIGACIÓN|47|C
UNAATRIBUCIÓN|47|
UNA FACULTAD|47|
UNA COMPETENCIA|47|
UNA FUNCIÓN|47|

UNA ATRIBUCIÓN DEL PERSONAL POLICIAL|48|
UNA COMPETENCIA DEL PERSONAL POLICIAL|48|
UNA FUNCIÓN DEL PERSONAL POLICIAL|48|
UNA FACULTAD DEL PERSONAL POLICIAL|48|
UN DERECHO DEL PERSONAL POLICIAL|48|C

CONSEJO DE ALTA DIRECCIÓN|49|
CONSEJO DE CALIFICACIÓN|49|
CONSEJOS DE INVESTIGACIÓN|49|
COMISIONES CONSULTIVAS|49|
ÓRGANOS DE ADMINISTRACIÓN INTERNA|49|C

ÓRGANOS DE ASESORAMIENTO|50|
ÓRGANOS DE APOYO POLICIAL|50|C
ÓRGANOS DE APOYO ADMINISTRATIVO|50|
COMISIONES CONSULTIVAS|50|
ÓRGANOS DE LÍNEA|50|

ÓRGANOS DESCONCENTRADOS|51|
ÓRGANOS DE ADMINISTRACIÓN INTERNA|51|
ÓRGANOS DE LÍNEA|51|C
MACROREGIONES POLICIALES|51|
ÓRGANOS DE APOYO POLICIAL|51|

PREVENCIÓN Y SEGURIDAD INTEGRAL|52|
CRIMINALÍSTICA|52|
INVESTIGACIÓN POLICIAL|52|
ÓRDEN PÚBLICO Y SEGURIDAD CIUDADANA|52|
CONTROL ADMINISTRATIVO DISCIPLINARIO|52|C

INSPECTORÍA GENERAL|53|
EL SISTEMA DISCIPLINARIOPOLICIAL|53|C
INSPECTORÍAS DESCENTRALIZADAS|53|
TRIBUNAL DE DISCIPLINA POLICIAL|53|
OFICINAS DE DISCIPLINA|53|

UNA ATRIBUCIÓN POLICIAL|54|
UN DEBER POLICIAL|54|
UNA FUNCIÓN POLICIAL|54|C
UNA OBLIGACIÓN POLICIAL|54|
UNA COMPETENCIA POLICIAL|54|

COMITÉ DE ASESORAMIENTO|55|
ÓRGANOS CONSULTIVOS|55|
ÓRGANOS DE ADMINISTRACIÓN INTERNA|55|
SECRETARÍA EJECUTIVA|55|C
COMISIONES CONSULTIVAS|55|

LEGALIDAD|56|
LA ARTICULACIÓN DE LAS INTERVENCIONES EN EL TERRITORIO NACIONAL|56|C
EFICIENCIA Y EFICACIA|56|
UNIDAD DE LA FUNCIÓN POLICIAL|56|
UNIDAD DE COMANDO|56|

UNA FACULTAD|57|
UN DERECHO|57|
UNA FUNCIÓN|57|
UNA COMPETENCIA|57|
UNA ATRIBUCIÓN|57|C

UNA PROHIBICIÓN|58|
UNA OBLIGACIÓN|58|
UNA FACULTAD|58|
UNA INCOMPATIBILIDAD|58|C
UN DERECHO|58|

UNA FACULTAD|59|
UN DERECHO|59|
UNA PROHIBICIÓN|59|C
UNA INCOMPATIBILIDAD|59|
UNA OBLIGACIÓN|59|

ÓRGANOS DESCONCENTRADOS|60|C
ÓRGANOS DE LÍNEA|60|
ÓRGANOS DE ADMINISTRACIÓN INTERNA|60|
ÓRGANOS CONSULTIVOS|60|
ÓRGANOS DE APOYO POLICIAL|60|